### PR TITLE
Update to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**
Close #38 
Close #44

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
lesson learned from the story: test your changes. Even if they seem to be harmless.

**Comment by hfiguiere** [comment]
bot, build

**Review by FakeShemp — APPROVED** [review]

**Pull request merged**
