### PR TITLE
Update KDE Runtime to 5.12 and dependencies

### PR DESCRIPTION
**Pull request by sat3ll**

### CODE REVIEW

**Comment by FakeShemp** [comment]
GStreamer and its plugins shouldn't be needed anymore as compatible versions are included in the runtime now. Have you tried without them?

**Comment by sat3ll** [comment]
If gstreamer and its plugins are not built, opus files will not play (tested with and without).

**Comment by TingPing** [comment]
> If gstreamer and its plugins are not built, opus files will not play (tested with and without).

That would be a bug in the runtime that should be reported, Opus is absolutely included.

**Comment by sat3ll** [comment]
> > If gstreamer and its plugins are not built, opus files will not play (tested with and without).
> 
> That would be a bug in the runtime that should be reported, Opus is absolutely included.

Its #3 we're facing again here. Any idea which gstreamer-plugins are shipped with the runtime / provide Opus?

**Comment by FakeShemp** [comment]
That should be "base".

**Comment by sat3ll** [comment]
Opened https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/622

**Comment by sat3ll** [comment]
No easy workaround that would work for multi-arch per: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/622#note_141004868.
Should we continue building our own gstreamer for the meantime?

**Comment by TingPing** [comment]
> Should we continue building our own gstreamer for the meantime?

Sure.

**Comment by sat3ll** [comment]
In that case, this PR is ready to be merged. I did not push the changes to disable the bundling of gstreamer.

**Pull request merged**
